# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('qty', 'Quantity')], db_index=True, default='percent', max_length=8)),
                ('description', models.CharField(default='discount', max_length=200)),
                ('base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('qty', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uom', models.CharField(choices=[('gr', 'grs'), ('ud', 'uds')], default='ud', max_length=2)),
                ('uom_factor', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('product_type', models.CharField(choices=[('other', 'Other'), ('main', 'Main dish'), ('drink', 'Drink'), ('dessert', 'Dessert')], db_index=True, default='other', max_length=8)),
                ('offer_3x2', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='discount',
            name='lines',
            field=models.ManyToManyField(to='shop.OrderLine'),
        ),
        migrations.AddField(
            model_name='discount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
